apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$rootProject.projectDir/shared-build.gradle"

android {
    compileSdk 36

    defaultConfig {
        targetSdk 36
        versionCode 110
    }
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.core:core-splashscreen:1.2.0'

    implementation 'androidx.wear:wear:1.4.0'

    implementation project(path: ':shared-models')
}